apiVersion: app/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployement
spec:
  replicas: 1
  selector:
    matchlabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
    containers:
    - image: nginx
      name:nginx
